from collections.abc import Awaitable, Callable
from typing import Any, Generic, TypeVar, overload
from typing_extensions import Self

T = TypeVar("T")
T1 = TypeVar("T1")


class CtxItem(Generic[T]):
    @classmethod
    def make(cls, name: str) -> CtxItem[T]: ...


class Contexts(dict[str, Any]):
    def copy(self) -> Self: ...
    @overload
    def __getitem__(self, item: CtxItem[T1]) -> T1: ...
    @overload
    def __getitem__(self, item: str) -> Any: ...
    @overload
    def __setitem__(self, key: CtxItem[T1], value: T1, /) -> None: ...
    @overload
    def __setitem__(self, key: str, value: Any, /) -> None: ...
    @overload  # type: ignore[override]
    def get(self, key: CtxItem[T1], default: None = None, /) -> T1 | None: ...
    @overload  # type: ignore[override]
    def get(self, key: str, default: None = None, /) -> Any | None: ...
    @overload
    def get(self, key: CtxItem[T1], default: T1, /) -> T1: ...
    @overload
    def get(self, key: CtxItem[T1], default: T, /) -> T1 | T: ...
    @overload
    def get(self, key: str, default: Any, /) -> Any: ...
    @overload
    def pop(self, key: CtxItem[T1], /) -> T1: ...
    @overload
    def pop(self, key: str, /) -> Any: ...
    @overload
    def pop(self, key: CtxItem[T1], default: T1, /) -> T1: ...
    @overload
    def pop(self, key: CtxItem[T1], default: T, /) -> T1 | T: ...
    @overload
    def pop(self, key: str, default: T, /) -> Any | T: ...
    def __delitem__(self, key: str | CtxItem, /) -> None: ...

EVENT: CtxItem[Any]
shared_suppliers: list[Callable[[Contexts], Awaitable[None]]]

async def generate_contexts(event: T, supplier:  Callable[[T, Contexts], Awaitable[Contexts | None]] | None = None, inherit_ctx: Contexts | None = None) -> Contexts: ...
