from collections.abc import Awaitable, Callable
from typing import Any, Generic, TypeVar, overload
from typing_extensions import Self

T = TypeVar("T")
T1 = TypeVar("T1")


class CtxItem(Generic[T]):
    @classmethod
    def make(cls, name: str) -> CtxItem[T]: ...


class Contexts(dict[str, Any]):
    def copy(self) -> Self: ...
    @overload
    def __getitem__(self, item: CtxItem[T1]) -> T1: ...
    @overload
    def __getitem__(self, item: str) -> Any: ...
    @overload
    def __setitem__(self, key: CtxItem[T1], value: T1, /) -> None: ...
    @overload
    def __setitem__(self, key: str, value: Any, /) -> None: ...
    @overload
    def get(self, __key: CtxItem[T1]) -> T1 | None: ...
    @overload
    def get(self, __key: str) -> Any | None: ...
    @overload
    def get(self, __key: CtxItem[T1], __default: T1) -> T1: ...
    @overload
    def get(self, __key: str, __default: Any) -> Any: ...
    @overload
    def get(self, __key: CtxItem[T1], __default: T) -> T1 | T: ...

EVENT: CtxItem[Any]
shared_suppliers: list[Callable[[Contexts], Awaitable[None]]]

async def generate_contexts(event: T, supplier:  Callable[[T, Contexts], Awaitable[Contexts | None]] | None = None, inherit_ctx: Contexts | None = None) -> Contexts: ...
